List=[]
SlicingOfElements1=[1,2,3]
SlicingOfElements2=[4,5,6]
SlicingOfElements3=[7,8,9]
List.append(SlicingOfElements1)
List.append(SlicingOfElements2)
List.append(SlicingOfElements3)
print(List)
print(List[0][0])
print(List[1][2])
print(List[2][1])
